# Builds and commits the artifacts whenever a change is pushed to main.
name: artifact compiler
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest stable
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Artifacts
        run: |
          ./devtools/optimize.sh
      - name: Commit artifacts
        run: |
          git config --global user.name 'DA0-DA0'
          git config --global user.email 'DA0-DA0@users.noreply.github.com'
          git add artifacts --force
          git commit -m "Update artifacts [skip ci]"
          git push
